baseURL = 'https://zephyrus-linux.stentijhuis.nl/'
title = 'Zephyrus Linux'
theme = 'hextra'
defaultContentLanguage = 'en'
enableRobotsTXT = true
enableGitInfo = true

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
    title = 'Zephyrus Linux'
  [languages.nl]
    languageName = 'Nederlands'
    weight = 2
    title = 'Zephyrus Linux'

[menu]
  [[menu.main]]
    identifier = 'docs'
    name = 'Guides'
    pageRef = '/docs'
    weight = 1
  [[menu.main]]
    name = 'Search'
    weight = 2
    [menu.main.params]
      type = 'search'
  [[menu.main]]
    name = 'GitHub'
    weight = 3
    url = 'https://github.com/Stensel8/Zephyrus-Linux'
    [menu.main.params]
      icon = 'github'

[params]
  description = 'Fedora Linux setup guides for the ASUS ROG Zephyrus G16 GA605WV â€” NVIDIA drivers, VM setup, YubiKey, and more.'

  [params.navbar]
    displayTitle = true
    displayLogo = false
    width = 'wide'

  [params.theme]
    default = 'system'
    displayToggle = true

  [params.footer]
    enable = true
    displayCopyright = false
    displayPoweredBy = false
    width = 'normal'

  displayUpdatedDate = true
  dateFormat = 'January 2, 2006'

  [params.search]
    enable = true
    type = 'flexsearch'
    [params.search.flexsearch]
      index = 'content'
      tokenize = 'forward'

  [params.editURL]
    enable = true
    base = 'https://github.com/Stensel8/Zephyrus-Linux/edit/main/content'

  [params.highlight]
    [params.highlight.copy]
      enable = true
      display = 'hover'

  [params.page]
    width = 'wide'

  [params.imageZoom]
    enable = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
